CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(250) NOT NULL,
    passwordinfo VARCHAR(50) NOT NULL,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    dbirth VARCHAR(100) NOT NULL,
    fakultet VARCHAR(50) NOT NULL,
    course VARCHAR(50) NOT NULL,
    gender VARCHAR(50) NOT NULL
);
